minimal:
  version_control:
    - git-core
    - subversion
    - mercurial
  build:
    - cmake
    - gcc
    - gcc-c++
    - gcc-gfortran
    - make
  util:
    - screen
    - unzip
    - tar
    - less
  network:
    - curl
    - wget
libraries:
  - bzip2-devel
  - freetype-devel
  - gsl-devel
  - libpng-devel
  - libz-devel
programming:
  - protobuf-c
  - protobuf-compiler
  - protobuf-python
  - openssl-devel
java:
  - ant
  - ant-junit
  - ant-nodeps
  - java-1.7.0-openjdk
  - java-1.7.0-openjdk-devel
  - junit4
python:
  - python
  - python-devel
  - boost-python-devel
  - numpy
distributed:
  - hadoop-0.20
  - hadoop-0.20-native
  - hadoop-0.20-pipes
  - hadoop-0.20-source
  - hadoop-0.20-libhdfs
