# Packages available in the Homebrew and Linuxbrew package manager
---
bio_nextgen:
  alignment:
    - bwa
    - bowtie2
    - novoalign
    - rna-star
  utilities:
    - bamtools
    - bedtools
    - libmaus
    - biobambam
    - fastqc
    - fastx_toolkit
    - qualimap
    - sambamba
  analysis:
    #- cufflinks
    - samtools
    #- tophat
  variant:
    - delly
    - freebayes
    - glia
    - lumpy-sv
    - platypus-variant
    - tabix
    - vcflib
    - vcftools
    - yaha
distributed:
  - parallel