# Packages available in the Homebrew and Linuxbrew package manager
---
bio_nextgen:
  alignment:
    #- bwa
    - bowtie2
    - novoalign
  utilities:
    #- bamtools
    - bedtools
    - fastqc
    - qualimap
    - sambamba
  analysis:
    #- cufflinks
    - samtools==0.1.19
    #- tophat
  variant:
    #- delly
    #- lumpy-sv
    - tabix
    - vcftools
    - yaha