---
# List of custom programs to install that are not packaged. These each require 
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.

bio_nextgen:
  alignment:
    - bwa
    - bowtie
    - perm
  analysis:
    - fastx_toolkit
    - gatk
    - picard
  assembly:
    - abyss
    - velvet
  needs_64bit:
    - ucsc_tools
    - bfast
    - novoalign
distributed:
  - mahout
  - pydoop
java:
  - leinengin
  - cljr
python:
  - bx_python
