---
# List of packages to be installed via the package manager.
#
# This is derived from the Infochimps machetEC2 package:
#
# http://github.com/infochimps/machetec2
#
# and merged with packages from bioperl-max:
#
# http://fortinbras.us/bioperl-max/
#
# and biolinux:
#
# http://www.jcvi.org/cms/research/projects/jcvi-cloud-biolinux/included-software/
#
# Package names are the terminal symbols in the tree (the text on any
# line which begins with whitespace followed by a hypen and a space).
#
# The package list is organized taxonomically so that parts of it can
# be selectively installed/ignored. See main.yaml for top level configuration.
programming:
  editors:
    - emacs
    - emacs-goodies-el
    - emacsen-common
    - vim
  version_control:
    - git-core
    - cvs
    - subversion
    - mercurial
    - bzr
    - darcs
  misc:
    - exuberant-ctags
  build:
    - swig
    - curl
    - libcurl4-openssl-dev
    - libxml2
    - libxml2-dev
    - libgsl0-dev
    - libgsl0ldbl
    - gsl-bin
    - xfsprogs
    - libc6-dev
    - libzip-dev
    - libncurses5-dev
  packaging:
    - build-essential
    - devscripts
    - debhelper
    - dh-make
    - pbuilder
  util:
    - tree
  lang:
    - aspell
    - dictionaries-common
    - libaspell-dev
# Note that the following Cloudera hadoop installation is for test
# purposes "inside the instance" only, Amazon already provides a
# production-ready Elastic MapReduce platform:
# http://aws.amazon.com/elasticmapreduce/
distributed:
  - hadoop-0.20
  - hadoop-pig
  - hadoop-hive
amazon:
  - s3cmd
  - ec2-ami-tools
  - ec2-api-tools
  - euca2ools
  - python-vm-builder-ec2
python:
  meta:
    - python
    - ipython
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python-distutils-extra
    - pyrex-mode
    - python-pyrex
    - python-dev
  utils:
    - python-dateutil
  wrappers:
    - libboost-dev
    - libboost-python-dev
    - python-libxslt1
    - python-libccc
    - python-libsvm
    - python-libxml2
    - bjam
    - boost-build
    - python-cairo
    - python-cairo-dev
    - python-mysqldb
    - python-openssl
    - pycaml
    - python-pysqlite2
    - python-bibtex
    - python-boto
    - python-cjson
    - python-couchdb
  math:
    - python-sympy
    - python-crypto
    - python-numeric
    - python-numpy
  viz:
    - python-reportlab
    - python-biggles
  # FIXME please organize this huge list better!
  misc:
    - python-beautifulsoup
    - python-constraint
    - python-cxx
    - python-cxx-dev
    - python-excelerator
    - python-extended-threading
    - python-fuse
    - python-gadfly
    - python-glpk
    - python-gmpy
    - python-gnuplot
    - python-gnutls
    - python-hippocanvas
    - python-ipy
    - python-irclib
    - python-jaxml
    - python-json
    - python-matplotlib
    - python-matplotlib-data
    - python-mode
    - python-networkx
    - python-nose
    - python-numpy-ext
    - python-plplot
    - python-pprocess
    - python-psycopg2
    - python-pycha
    - python-pychart
    - python-pydot
    - python-pygooglechart
    - python-pygraphviz
    - python-pyme
    - python-pymssql
    - python-pyode
    - python-pywt
    - python-pyx
    - python-reportlab-accel
    - python-reverend
    - python-rrdtool
    - python-scientific
    - python-scipy
    - python-sparse
    - python-sparse-examples
    - python-sqlalchemy
    - python-sqlite
    - python-sqlitecachec
    - python-sqlobject
    - python-sqlrelay
    - python-statgrab
    - python-stats
    - python-symeig
    - python-sympy
    - python-testresources
    - python-visual
    - python-xlrd
    - python-yapgvb
    - python-lxml
ruby:
  # ruby gems are installed by components/ruby.rb
  - rubygems
  - ruby1.8-dev
  - irb
  - ri
  - rdoc
  - rake
  - libmysql-ruby
  - libxml-ruby
  - libsqlite3-ruby
  - libbio-ruby
  - libbio-ruby1.8
r:
  - r-base
  - r-base-core
  - r-base-core-ra
  - r-base-dev
  - r-base-html
  - r-cran-date
perl: 
  - perl
  - libmoose-perl
  - parrot
  - parrot-devel
  - bioperl
  - bioperl-run
java:
  - sun-java6-bin
  - sun-java6-jre
  - sun-java6-jdk
  - openjdk-6-jdk
  - openjdk-6-jre
  - ant
  - libbiojava-java
  - eclipse
  - maven2
  - libjline-java
  - clojure
erlang:
  - erlang
  - erlang-base
  - erlang-dev
  - erlang-examples
  - erlang-manpages
  - erlang-mode
haskell:
  - ghc6
  - libghc6-mtl-dev
  - libghc6-network-dev
  - libghc6-parsec2-dev
  - libghc6-parsec3-dev
  - libghc6-quickcheck1-dev
  - libghc6-quickcheck2-dev
  - libghc6-tagsoup-dev
  - libghc6-utf8-string-dev
  - libghc6-x11-dev
  - libghc6-x11-xft-dev
databases:
  mysql:
    - mysql-client
    - mysql-common
    - mysql-server
    - libmysqlclient15-dev
  postgres:
    - postgresql
    - postgresql-client
    - postgresql-plpython-8.4
    - postgresql-plperl-8.4
  sqlite:
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
  document:
    - mongodb-stable
    - couchdb
    - tokyocabinet-bin
    - libtokyocabinet8
    - libtokyocabinet-dev
math:
  - prover9
  - octave3.0
viz:
  - x11-apps
  - mayavi2
  - mtasc # for modest maps
  - graphviz
  - libgraphviz-dev
web:
  - apache2
bio_general:
  - emboss
  - emboss-data
  - emboss-lib
  - primer3
  - readseq
  - bio-linux-taverna
bio_search:
  - blast2
  - hmmer
  - ncbi-tools-bin
  - bio-linux-blast+
  - bio-linux-blixem
  - bio-linux-fasta
  - bio-linux-mspcrunch
  - bio-linux-mview
  - bio-linux-nrdb
bio_alignment:
  - clustalw
  - exonerate
  - mafft
  - muscle
  - mummer
  - probcons
  - t-coffee
  - seaview
  - bio-linux-clustal
  - bio-linux-dotter
  - bio-linux-jalview
  - bio-linux-pfaat
  - bio-linux-prank
  - bio-linux-squint
  - bio-linux-wise2
bio_nextgen:
  - maq
  - samtools
# Package is old version, in custom: - bwa
bio_sequencing:
  - bio-linux-assembly-conversion-tools
  - bio-linux-cap3
  - bio-linux-dust
  - bio-linux-mira
  - bio-linux-mira-3rd-party
  - bio-linux-msatfinder
  - bio-linux-staden
  - bio-linux-stars
  - bio-linux-trace2dbest
bio_annotation:
  - mcl
  - tigr-glimmer
  - bio-linux-act
  - bio-linux-artemis
  - bio-linux-big-blast
  - bio-linux-cd-hit
  - bio-linux-estscan
  - bio-linux-glimmer3
  - bio-linux-partigene
  - bio-linux-priam
  - bio-linux-prot4est
  - bio-linux-rbs-finder
  - bio-linux-transterm-hp
  - bio-linux-trnascan
# Package broken: - bio-linux-yamap
  - bio-linux-tetra
bio_microarray:
  - bio-linux-ocount
  - bio-linux-oligoarray
  - bio-linux-oligoarrayaux
bio_visualization:
  - rasmol
  - bio-linux-clcsequenceviewer
  - bio-linux-maxd
bio_utils:
  - bio-linux-das-prep
  - bio-linux-exchanger
  - bio-linux-genquery
  - bio-linux-handlebar
  - bio-linux-keyring
  - bio-linux-base-directories
  - bio-linux-backups
  - bio-linux-bldp-files
  - bio-linux-pedro
  - bio-linux-envbase-for-pedro
  - bio-linux-sampledata
  - bio-linux-sequin
  - bio-linux-taxinspector
  - bio-linux-themes
  - bio-linux-themes-v5
  - bio-linux-usb-maker
phylogeny:
  - phylip
  - phyml
  - mrbayes
  - njplot
  - tree-puzzle
  - bio-linux-coalesce
  - bio-linux-dendroscope
  - bio-linux-fastDNAml
  - bio-linux-fluctuate
  - bio-linux-forester
  - bio-linux-happy
  - bio-linux-mesquite
  - bio-linux-migrate
  - bio-linux-mrbayes-multi
  - bio-linux-mothur
  - bio-linux-paml
  - bio-linux-omegamap
  - bio-linux-qtlcart
  - bio-linux-recombine
  - bio-linux-splitstree
  - bio-linux-treeview
# To Add -- need packages
# from bioperl-max:
#   hyphy
#   bioperl-db
#   more perl modules
# from bio-linux:
#   Celera Assembler
#   arb
#   genespring-2
#   gsrint
#   lamarc
#   lucy
#   peptidemapper
#   pftools
#   transterm
# Others:
#   bowtie
#   fastx-toolkit
#   mdust
#   Picard
#   GATK
#   IGV
#   trimpoly
#   blast2go
#   sputnik: microsattelites
#   GenomeView
#   UCSC: liftOver, faToTwoBit
