---
# List of packages to be installed via the package manager.
#
# This is derived from the Infochimps machetEC2 package:
#
# http://github.com/infochimps/machetec2
#
# and merged with packages from bioperl-max:
#
# http://fortinbras.us/bioperl-max/
#
# and biolinux:
#
# http://www.jcvi.org/cms/research/projects/jcvi-cloud-biolinux/included-software/
#
# Package names are the terminal symbols in the tree (the text on any
# line which begins with whitespace followed by a hypen and a space).
#
# The package list is organized taxonomically so that parts of it can
# be selectively installed/ignored. See main.yaml for top level configuration.
desktop:
  #Packages to support a remote desktop
  - gnome-panel
  - gnome-system-tools
  - synaptic
  - software-center
  - freenx
  - gnome-themes
  - gnome-backgrounds
  - gnome-terminal
  - firefox
  - cloudbl-desktop
programming:
  editors:
    - emacs
    - emacs-goodies-el
    - emacsen-common
    - vim
  version_control:
    - git-core
    - cvs
    - subversion
    - mercurial
    - bzr
    - darcs
  misc:
    - exuberant-ctags
  build:
    - swig
    - curl
    - libcurl4-openssl-dev
    - libxml2
    - libxml2-dev
    - libgsl0-dev
    - libgsl0ldbl
    - gsl-bin
    - xfsprogs
    - libc6-dev
    - libzip-dev
    - libbz2-dev
    - libgtk2.0-dev
    - libncurses5-dev
    - zlib1g-dev
    - libssl-dev
    - libpcre3-dev
    - libreadline5-dev
    - gcc 
    - g++
    - stow
  packaging:
    - build-essential
    - devscripts
    - debhelper
    - dh-make
    - pbuilder
    - unzip
  util:
    - nfs-kernel-server
    - tree
  lang:
    - aspell
    - dictionaries-common
    - libaspell-dev
  galaxy:
    - rabbitmq-server
# Note that the following Cloudera hadoop installation is for test
# purposes "inside the instance" only, Amazon already provides a
# production-ready Elastic MapReduce platform:
# http://aws.amazon.com/elasticmapreduce/
distributed:
  - hadoop-0.20
  - hadoop-pig
  - hadoop-hive
amazon:
  - s3cmd
  - ec2-ami-tools
  - ec2-api-tools
  - euca2ools
  - python-vm-builder-ec2
python:
  meta:
    - python
    - ipython
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python-distutils-extra
    - pyrex-mode
    - python-pyrex
    - python-dev
  utils:
    - python-dateutil
  wrappers:
    - libboost-dev
    - libboost-python-dev
    - python-libxslt1
    - python-libccc
    - python-libsvm
    - python-libxml2
    - bjam
    - boost-build
    - python-cairo
    - python-cairo-dev
    - python-mysqldb
    - python-openssl
    - pycaml
    - python-pysqlite2
    - python-bibtex
    - python-boto
    - python-cjson
    - python-couchdb
    - python-tables
    - python-h5py
  math:
    - python-sympy
    - python-crypto
    - python-numeric
    - python-numpy
  viz:
    - python-reportlab
    - python-biggles
  # FIXME please organize this huge list better!
  misc:
    - python-beautifulsoup
    - python-constraint
    - python-cxx
    - python-cxx-dev
    - python-excelerator
    - python-extended-threading
    - python-fuse
    - python-gadfly
    - python-glpk
    - python-gmpy
    - python-gnuplot
    - python-gnutls
    - python-hippocanvas
    - python-ipy
    - python-irclib
    - python-jaxml
    - python-json
    - python-matplotlib
    - python-matplotlib-data
    - python-mode
    - python-networkx
    - python-nose
    - python-numpy-ext
    - python-plplot
    - python-pprocess
    - python-psycopg2
    - python-pycha
    - python-pychart
    - python-pydot
    - python-pygooglechart
    - python-pygraphviz
    - python-pyme
    - python-pymssql
    - python-pyode
    - python-pywt
    - python-pyx
    - python-reportlab-accel
    - python-reverend
    - python-rrdtool
    - python-scientific
    - python-scipy
    - python-sparse
    - python-sparse-examples
    - python-sqlalchemy
    - python-sqlite
    - python-sqlitecachec
    - python-sqlobject
    - python-sqlrelay
    - python-statgrab
    - python-stats
    - python-symeig
    - python-sympy
    - python-testresources
    - python-visual
    - python-xlrd
    - python-yapgvb
    - python-lxml
ruby:
  # ruby gems are installed by components/ruby.rb
  - rubygems
  - ruby1.8-dev
  - irb
  - ri
  - rdoc
  - rake
  - libmysql-ruby
  - libxml-ruby
  - libsqlite3-ruby
  - libbio-ruby
  - libbio-ruby1.8
r:
  - r-base
  - r-base-core
  - r-base-core-ra
  - r-base-dev
  - r-base-html
  - r-cran-abind
  - r-cran-boot
  - r-cran-car
  - r-cran-chron
  - r-cran-class
  - r-cran-cluster
  - r-cran-codetools
  - r-cran-colorspace
  - r-cran-date
  - r-cran-effects
  - r-cran-foreign
  - r-cran-hdf5
  - r-cran-hmisc
  - r-cran-kernsmooth
  - r-cran-lattice
  - r-cran-lmtest
  - r-cran-mass
  - r-cran-matrix
  - r-cran-mgcv
  - r-cran-multcomp
  - r-cran-mvtnorm
  - r-cran-nlme
  - r-cran-nnet
  - r-cran-rcmdr
  - r-cran-relimp
  - r-cran-rgl
  - r-cran-rpart
  - r-cran-sandwich
  - r-cran-sm
  - r-cran-spatial
  - r-cran-strucchange
  - r-cran-survival
  - r-cran-vgam
  - r-cran-vr
  - r-cran-zoo
perl: 
  - perl-base
  - perl
  - perl-modules
  - perl-tk
  - libperl-dev
  - libmoose-perl
  - parrot
  - parrot-devel
  - bioperl
  - bioperl-run
  - librpc-xml-perl
  - libtext-iconv-perl
  - libace-perl
  - libalgorithm-c3-perl
  - libalgorithm-diff-perl
  - libalgorithm-munkres-perl
  - libanydata-perl
  - libapparmor-perl
  - libarray-compare-perl
  - libbio-asn1-entrezgene-perl
  - libbit-vector-perl
  - libcache-cache-perl
  - libcairo-perl
  - libcarp-assert-perl
  - libcarp-clan-perl
  - libcgi-application-basic-plugin-bundle-perl
  - libcgi-application-perl
  - libcgi-application-plugins-perl
  - libcgi-session-perl
  - libclass-accessor-perl
  - libclass-c3-perl
  - libclass-c3-xs-perl
  - libclass-data-inheritable-perl
  - libclass-inspector-perl
  - libclass-mop-perl
  - libclone-perl
  - libconfig-auto-perl
  - libconfig-inifiles-perl
  - libconfig-simple-perl
  - libconvert-binary-c-perl
  - libconvert-binhex-perl
  - libcrypt-ssleay-perl
  - libdata-formvalidator-perl
  - libdata-optlist-perl
  - libdata-stag-perl
  - libdate-calc-perl
  - libdate-manip-perl
  - libdbd-anydata-perl
  - libdbd-csv-perl
  - libdbd-mysql-perl
  - libdbd-pg-perl
  - libdbd-sqlite3-perl
  - libdbi-perl
  - libdevel-globaldestruction-perl
  - libdevel-stacktrace-perl
  - libdigest-hmac-perl
  - libdigest-sha1-perl
  - libemail-valid-perl
  - liberror-perl
  - libexception-class-perl
  - libexception-class-trycatch-perl
  - libfcgi-perl
  - libfile-copy-recursive-perl
  - libfile-mmagic-perl
  - libfile-slurp-perl
  - libfile-which-perl
  - libfont-afm-perl
  - libfreezethaw-perl
  - libgd-gd2-noxpm-perl
  - libgd-graph-perl
  - libgd-text-perl
  - libglib-perl
  - libgnome2-canvas-perl
  - libgnome2-perl
  - libgnome2-vfs-perl
  - libgraph-perl
  - libgraphviz-perl
  - libgtk2-perl
  - libheap-perl
  - libhtml-fillinform-perl
  - libhtml-format-perl
  - libhtml-parser-perl
  - libhtml-tagset-perl
  - libhtml-template-perl
  - libhtml-tree-perl
  - libimage-size-perl
  - libio-pty-perl
  - libio-socket-ssl-perl
  - libio-string-perl
  - libio-stringy-perl
  - libipc-run-perl
  - libipc-sharelite-perl
  - libipc-signal-perl
  - libjcode-pm-perl
  - liblist-moreutils-perl
  - liblocale-gettext-perl
  - liblog-dispatch-perl
  - libmailtools-perl
  - libmath-derivative-perl
  - libmath-spline-perl
  - libmime-tools-perl
  - libmime-types-perl
  - libmldbm-perl
  - libmoose-perl
  - libmro-compat-perl
  - libnet-daemon-perl
  - libnet-dbus-perl
  - libnet-dns-perl
  - libnet-domain-tld-perl
  - libnet-ip-perl
  - libnet-libidn-perl
  - libnet-ssleay-perl
  - libole-storage-lite-perl
  - libossp-uuid-perl
  - libpango-perl
  - libparams-util-perl
  - libparams-validate-perl
  - libparse-debianchangelog-perl
  - libparse-recdescent-perl
  - libperl5.10
  - libperl6-junction-perl
  - libplrpc-perl
  - libpod-xhtml-perl
  - libpostscript-perl
  - libproc-invokeeditor-perl
  - libproc-waitstat-perl
  - libregexp-common-perl
  - librpc-xml-perl
  - libscope-guard-perl
  - libset-scalar-perl
  - libsoap-lite-perl
  - libspreadsheet-parseexcel-perl
  - libspreadsheet-parseexcel-simple-perl
  - libspreadsheet-writeexcel-perl
  - libsql-statement-perl
  - libstatistics-descriptive-perl
  - libsub-exporter-perl
  - libsub-install-perl
  - libsub-name-perl
  - libsub-uplevel-perl
  - libsvg-graph-perl
  - libsvg-perl
  - libsyntax-highlight-perl-improved-perl
  - libtask-weaken-perl
  - libterm-readkey-perl
  - libtest-exception-perl
  - libtext-charwidth-perl
  - libtext-csv-perl
  - libtext-csv-xs-perl
  - libtext-iconv-perl
  - libtext-wrapi18n-perl
  - libtie-ixhash-perl
  - libtimedate-perl
  - libtree-dagnode-perl
  - libtry-tiny-perl
  - libunicode-map-perl
  - libuniversal-require-perl
  - liburi-perl
  - libuuid-perl
  - libwww-perl
  - libxml-dom-perl
  - libxml-dom-xpath-perl
  - libxml-filter-buffertext-perl
  - libxml-libxml-perl
  - libxml-libxslt-perl
  - libxml-namespacesupport-perl
  - libxml-parser-perl
  - libxml-perl
  - libxml-regexp-perl
  - libxml-sax-expat-perl
  - libxml-sax-perl
  - libxml-sax-writer-perl
  - libxml-simple-perl
  - libxml-twig-perl
  - libxml-writer-perl
  - libxml-xpathengine-perl
  - libxml-xpath-perl
  - libyaml-perl
  - libyaml-syck-perl
java:
  - sun-java6-bin
  - sun-java6-jre
  - sun-java6-jdk
  - openjdk-6-jdk
  - openjdk-6-jre
  - ant
  - libbiojava-java
  - libbiojava-java-demos
  - eclipse
  - maven2
  - libjline-java
  - libjhdf5-java
  - clojure
  - jruby
  - jython
  - scala
  - scala-library
erlang:
  - erlang
  - erlang-base
  - erlang-dev
  - erlang-examples
  - erlang-manpages
  - erlang-mode
  - rabbitmq-server
haskell:
  - ghc6
  - libghc6-mtl-dev
  - libghc6-network-dev
  - libghc6-parsec2-dev
  - libghc6-parsec3-dev
  - libghc6-quickcheck1-dev
  - libghc6-quickcheck2-dev
  - libghc6-tagsoup-dev
  - libghc6-utf8-string-dev
  - libghc6-x11-dev
  - libghc6-x11-xft-dev
databases:
  mysql:
    - mysql-client
    - mysql-common
    - mysql-server
    - libmysqlclient15-dev
  postgres:
    - postgresql
    - postgresql-client
    - postgresql-plpython-8.4
    - postgresql-plperl-8.4
  sqlite:
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
  document:
    - mongodb-stable
    - couchdb
    - tokyocabinet-bin
    - libtokyocabinet8
    - libtokyocabinet-dev
  hdf:
    - libhdf5-serial-1.8.4
    - libhdf5-serial-dev
math:
  - prover9
  - octave3.0
viz:
  - x11-apps
  - mayavi2
  - mtasc # for modest maps
  - graphviz
  - libgraphviz-dev
  - libgl1-mesa-dev
  - libgl1-mesa-dri
  - libgl1-mesa-glx
  - libglu1-mesa
  - libglu1-mesa-dev
web:
  - apache2
bio_general:
  - emboss
  - emboss-data
  - emboss-lib
  - primer3
  - readseq
  - bio-linux-taverna
  - bio-linux-xcut
bio_search:
  - blast2
  - hmmer
  - ncbi-tools-bin
  - bio-linux-blast+
  - bio-linux-blixem
  - bio-linux-fasta
  - bio-linux-mspcrunch
  - bio-linux-mview
  - bio-linux-nrdb
bio_alignment:
  - clustalw
  - exonerate
  - mafft
  - muscle
  - mummer
  - probcons
  - t-coffee
  - seaview
  - bio-linux-clustal
  - bio-linux-dotter
  - bio-linux-jalview
  - bio-linux-pfaat
  - bio-linux-prank
  - bio-linux-squint
  - bio-linux-wise2
bio_nextgen:
  - maq
  - samtools
# Package is old version, in custom: - bwa
bio_sequencing:
  - bio-linux-assembly-conversion-tools
  - bio-linux-cap3
  - bio-linux-dust
  - bio-linux-lucy
  - bio-linux-mira
  - bio-linux-mira-3rd-party
  - bio-linux-msatfinder
  - bio-linux-staden
  - bio-linux-stars
bio_annotation:
  - mcl
  - tigr-glimmer
  - bio-linux-act
  - bio-linux-artemis
  - bio-linux-big-blast
  - bio-linux-cd-hit
  - bio-linux-estscan
  - bio-linux-glimmer3
  - bio-linux-partigene
  - bio-linux-priam
  - bio-linux-prot4est
  - bio-linux-rbs-finder
  - bio-linux-transterm-hp
  - bio-linux-trnascan
# Package broken: - bio-linux-yamap
  - bio-linux-tetra
bio_microarray:
  - bio-linux-ocount
  - bio-linux-oligoarray
  - bio-linux-oligoarrayaux
bio_visualization:
  - rasmol
  - bio-linux-clcsequenceviewer
  - bio-linux-maxd
bio_utils:
  - bio-linux-das-prep
  - bio-linux-exchanger
  - bio-linux-genquery
  - bio-linux-keyring
  - bio-linux-base-directories
  - bio-linux-bldp-files
  - bio-linux-sampledata
  - bio-linux-sequin
  - bio-linux-taxinspector
  - bio-linux-themes-v5
phylogeny:
  all:
    - phylip
    - phyml
    - mrbayes
    - njplot
    - tree-puzzle
    - bio-linux-arb
    - bio-linux-coalesce
    - bio-linux-dendroscope
    - bio-linux-fastDNAml
    - bio-linux-fluctuate
    - bio-linux-forester
    - bio-linux-happy
    - bio-linux-mesquite
    - bio-linux-migrate
    - bio-linux-mrbayes-multi
    - bio-linux-mothur
    - bio-linux-paml
    - bio-linux-omegamap
    - bio-linux-qtlcart
    - bio-linux-recombine
    - bio-linux-splitstree
    - bio-linux-treeview
  needs_64bit:
    - bio-linux-fasttree
#
#
# To Add -- need packages
# from bioperl-max:
#   hyphy
#   bioperl-db
#   more perl modules
# from bio-linux:
#   Celera Assembler
#   lamarc - not available just now (22/6/10)
#   peptidemapper
#   pftools
#   transterm
# Others:
#   mdust
#   Picard
#   GATK
#   IGV
#   trimpoly
#   blast2go
#   sputnik: microsattelites
#   GenomeView
