---
# Configuration file defining perl libraries to install via CPAN
cpan:
# build
  - 'Test::More'
  - 'Module::Build'
  - 'Test::Harness'
  - 'ExtUtils::Manifest'
  - 'ExtUtils::ModuleMaker'
  - 'YAML'
  - 'Digest::MD5'
  - 'Digest::SHA1'
  # bioperl-live deps
  - 'IO::String'
  - 'Data::Stag'
  - 'Scalar::Util'
  - 'Ace'
  - 'Algorithm::Munkres'
  - 'Algorithm::Diff'
  - 'Array::Compare'
  - 'Clone'
  - 'Convert::Binary::C'
  - 'Graph'
  - 'HTML::Entities'
  - 'HTML::HeadParser'
  - 'GraphViz'
  - 'Bundle::LWP'
  - 'IPC::Run'
  - 'IO::String'
  - 'List::MoreUtils'
  - 'Math::Random'
  - 'PostScript::TextBlock'
  - 'Set::Scalar'
  - 'SOAP::Lite'
  - 'Sort::Naturally'
  - 'Spreadsheet::ParseExcel'
  - 'Storable'
  - 'SVG'
  - 'SVG::Graph'
  - 'Text::ParseWords'
  - 'URI::Escape'
  - 'XML::DOM::XPath'
  - 'XML::Parser'
  - 'XML::Parser::PerlSAX'
  - 'XML::SAX'
  - 'XML::SAX::Writer'
  - 'XML::Simple'
  - 'XML::Twig'
  - 'XML::Writer'
  # my recs
  - 'Inline'
  - 'XML::LibXML '
  - 'IO::Compress::Base'
  - 'IO::Compress::Bzip2'
  - 'IO::Compress::Lzf'
  # Database drivers
  - 'DBI'
  - 'DBD::SQLite'
  - 'DBD::mysql'
  # Biome : these will definitely be added to over time
  - 'Modern::Perl'
  - 'Moose'
  - 'IO::Unread'
  - 'MooseX::ClassAttribute'
  - 'MooseX::Types'
  - 'MooseX::Role::Parameterized'
  - 'MooseX::Aliases'
  # Lincoln's, not BioPerl 
  - 'Bio::Graphics'
# Currently have problems building
#  - 'DB_File'
#  - 'DBD::Pg'
#  These need samtools and Jim Kent's source trees so need to be done by hand
#  - 'Bio::DB::Sam'
#  - 'Bio::DB::BigFile'
