---
# Configuration file defining python specific libraries on pypi to install
# using easy install
pypi:
  - biopython
  - cogent
  - DendroPy
  - HTSeq
  - rpy2
  - rpy2-bioconductor-extensions
  - bx-python 
  - pymongo
# Pulls the wrong file and then can't install automatically
#  - pygr
# Should get into pypi
#  - pysam
