---
# Configuration file defining python specific libraries on pypi to install
# using easy install
pypi:
  # science
  - biopython
  - cogent
  - DendroPy
  - HTSeq
  - networkx
  - numpy
  - pygr
  - pysam
  - pysparse
  - rpy2
  - rpy2-bioconductor-extensions
  - ScientificPython
  - scipy
  - sympy
  # databases
  - CouchDB
  - h5py
  - MySQL-python
  - pymongo
  - pymssql
  - pysqlite
  - psycopg2
  - SQLAlchemy
  - tables
  # visualization
  - gnuplot-py
  - matplotlib
  - pycairo
  - pydot
  - pygooglechart
  - pygraphviz
  - reportlab
  # infrastructure
  - amqplib
  - BeautifulSoup
  - boto
  - fabric
  - ipython
  - Logbook
  - lxml
  - mako
  - nose
  - paste
  - pastescript
  - pycrypto
  - python-cjson
  - pyOpenSSL
  - pyyaml
  - routes
  - simplejson
  - webhelpers
  - webob
  - xlrd
  # build
  - cython
  - Pyrex
  - virtualenv
