---
# Configuration file defining python specific libraries on pypi to install
# using easy install
pypi:
  - cython
  - biopython
  - cogent
  - DendroPy
  - HTSeq
  - pysam
  - rpy2
  - rpy2-bioconductor-extensions
  - pymongo
  - pyyaml
  - fabric
  - gnuplot-py
  - simplejson
  - amqplib
  - boto
  - Logbook
  - PyYAML
  - pygr
  - mako
  - paste
  - routes
  - webhelpers
  - pastescript
  - webob
