---
# Configuration file defining R specific libraries that are installed 
# via CRAN and Bioconductor.
cranrepo: http://software.rc.fas.harvard.edu/mirrors/R/
cran:
 - ape
 - caTools
 - ggplot2
 - multicore
 - NMF
 - rjson
 - snowfall
 - sqldf
biocrepo: http://bioconductor.org/biocLite.R
bioc:
 - biomaRt
 - Biostrings
 - BSgenome
 - edgeR
 - GEOquery
 - GO.db
 - GOstats
 - KEGG.db
 - MotIV
 - org.Hs.eg.db
 - org.Mm.eg.db
 - PICS
 - rGADEM
 - Rsamtools
 - rtracklayer
 - ShortRead
