---
# Configuration file defining R specific libraries that are installed 
# via CRAN and Bioconductor.
cranrepo: http://software.rc.fas.harvard.edu/mirrors/R/
cran:
 - ape
 - aplpack
 - BiodiversityR
 - bitops
 - caTools
 - chron
 - coin
 - DBI
 - DynDoc
 - gee
 - ggplot2
 - HH
 - hwriter
 - leaps
 - mclust
 - modeltools
 - multicore
 - NMF
 - plotrix
 - RColorBrewer
 - RCurl
 - rjson
 - RSQLite
 - snowfall
 - sqldf
 - vegan
 - xtable
biocrepo: http://bioconductor.org/biocLite.R
bioc:
 - affy
 - affydata
 - affyio
 - affyPLM
 - affyQCReport
 - annaffy
 - annotate
 - AnnotationDbi
 - Biobase
 - biomaRt
 - Biostrings
 - BSgenome
 - edgeR
 - gcrma
 - genefilter
 - geneplotter
 - GenomicRanges
 - GEOquery
 - GO.db
 - GOstats
 - hgu95av2.db
 - KEGG.db
 - limma
 - marray
 - multtest
 - MotIV
 - org.Hs.eg.db
 - org.Mm.eg.db
 - preprocessCore
 - PICS
 - rGADEM
 - Rolexa
 - Rsamtools
 - rtracklayer
 - simpleaffy
 - ShortRead
 - vsn
