---
# Configuration file defining R specific libraries that are installed 
# via CRAN and Bioconductor.
cranrepo: http://software.rc.fas.harvard.edu/mirrors/R/
cran:
 - abind
 - ape
 - aplpack
 - BiodiversityR
 - bitops
 - car
 - caTools
 - chron
 - coin
 - colorspace
 - DBI
 - DynDoc
 - effects
 - gee
 - ggplot2
 - HH
 - Hmisc
 - hwriter
 - multicore
 - NMF
 - rjson
 - snowfall
 - sqldf
biocrepo: http://bioconductor.org/biocLite.R
bioc:
 - affy
 - affydata
 - affyio
 - affyPLM
 - affyQCReport
 - annaffy
 - annotate
 - AnnotationDbi
 - Biobase
 - biomaRt
 - Biostrings
 - BSgenome
 - edgeR
 - gcrma
 - genefilter
 - geneplotter
 - GenomicRanges
 - GEOquery
 - GO.db
 - hgu95av2.db
 - GOstats
 - KEGG.db
 - MotIV
 - org.Hs.eg.db
 - org.Mm.eg.db
 - PICS
 - rGADEM
 - Rsamtools
 - rtracklayer
 - ShortRead
