---
# Configuration file defining ruby libraries to install
# using gem install (avoiding the distribution package manager)
gems:
  - bio
  - fastercsv
  - hpricot
  - htmlentities
  - json
  - kwalify
  - libxml-ruby
  - uuidtools
  - xml-simple
  - sqlite3-ruby
  - do_sqlite3
  - data_objects
  - do_mysql
  - mysql
  - couchdb-ruby
  - datamapper
  - dm-adjust
  - dm-aggregates
  - dm-ar-finders
  - dm-cli
  - dm-constraints
  - dm-core
  - dm-ferret-adapter
  - dm-is-list
  - dm-is-nested_set
  - dm-is-remixable
  - dm-is-searchable
  - dm-is-state_machine
  - dm-is-tree
  - dm-is-versioned
  - dm-migrations
  - dm-observer
  - dm-rest-adapter
  - dm-serializer
  - dm-sweatshop
  - dm-tags
  - dm-timestamps
  - dm-types
  - dm-validations
  - cheat
  - addressable
  - vagrant
